version: '3'
services:
  react-front:
    image: masterweb87/react-app:latest
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app